# delayed_job config
Delayed::Worker.backend = :active_record
Delayed::Worker.destroy_failed_jobs = false
#Delayed::Worker.sleep_delay = 5
Delayed::Worker.max_attempts = 10
Delayed::Worker.max_run_time = 10.minutes
#Delayed::Worker.default_priority = 0
#Delayed::Worker.delay_jobs = true
#Delayed::Worker.queues = []
#Delayed::Worker.read_ahead = 5
