source 'http://rubygems.org'
ruby "2.0.0"
gem 'rake', '0.9.6'
gem 'rails', '3.1.10'
gem 'inherited_resources'

# HTML & CSS
gem 'haml'
gem 'haml-rails'

# gem 'mongrel'

gem 'devise'
gem 'cancan'

gem 'devise-token_authenticatable'

gem 'hpricot'

gem 'activegrid', "1.0.8"
gem "SystemTimer", :require => "system_timer", :platforms => :ruby_18
gem "rack-timeout"
gem 'newrelic_rpm'


gem 'hirb'
gem 'prawn'
gem "prawn-graph", :git => "git://github.com/HHRy/prawn-graph"

gem "mail"

gem 'sendgrid'
gem 'will_paginate'
gem 'rspec-rails'
gem 'delayed_job_active_record', :git => 'git://github.com/collectiveidea/delayed_job_active_record.git'


# gem "rmagick"
gem "carrierwave"

# fog is used by carrierwave to deal with s3
gem 'fog'

gem 'httparty'

group :development, :test do # <<<< :development, not devlopment
  gem 'sqlite3'
  gem 'taps'
end

group :assets do
  gem 'sass-rails',   " ~> 3.1.0"

  gem 'uglifier'
end

gem 'jquery-rails'

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger (ruby-debug for Ruby 1.8.7+, ruby-debug19 for Ruby 1.9.2+)
# gem 'ruby-debug'
# gem 'ruby-debug19'

# Bundle the extra gems:
# gem 'bj'
# gem 'nokogiri'
# gem 'sqlite3-ruby', :require => 'sqlite3'
# gem 'aws-s3', :require => 'aws/s3'

# Bundle gems for the local environment. Make sure to
# put test-only gems in this group so their generators
# and rake tasks are available in development mode:

group :test do
  gem "factory_girl_rails"

  gem "guard-rspec"
  gem "growl_notify"
  gem 'database_cleaner'
  gem 'shoulda-matchers'
  gem 'shoulda-context'
end


group :production do
  gem 'pg'
end
